name: 'Terraform Checks'

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Format & Validate'
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Se usa el GITHUB_TOKEN para permitir commit y push

      # Paso 2: Configurar Terraform sin backend remoto
      - name: Initialize Terraform without backend
        run: terraform init -backend=false

      # Paso 3: Comprobación de Formato con terraform fmt y exportar errores
      - name: Terraform Format Check with Diff
        run: terraform fmt -check -diff > format_errors.txt
        continue-on-error: true

      # Paso 4: Validación de los archivos con terraform validate
      - name: Terraform Validate
        run: terraform validate
        continue-on-error: true

      # Paso 5: Mostrar los errores de formato
      - name: Show Format Errors
        run: cat format_errors.txt

  # Job separado para aplicar terraform fmt si se aprueba y revision final de los cambios realizados 
  terraform_format:
    name: 'Apply Terraform Fmt'
    runs-on: ubuntu-latest
    environment: git-sensible-info
    needs: terraform  # Solo se ejecuta después de que el primer job termine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Apply Terraform Fmt
        run: terraform fmt

      - name: Show Git User Info
        run: |
          echo "User: ${{ secrets.GIT_USER_NAME }}"
          echo "Email: ${{ secrets.GIT_USER_EMAIL }}"
    
    # Paso 8: Comprobar si hubo cambios y ejecutar git diff solo si los hay
      - name: Check for modifications and show diff
        run: |
          if git diff --quiet; then
            echo "No changes detected";
          else
            git config user.name "${{ secrets.GIT_USER_NAME }}"
            git config user.email "${{ secrets.GIT_USER_EMAIL }}"
            git add .
            git commit -m "Apply terraform fmt changes"
            git push
          fi