name: Deploy Helm Charts to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2.1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan -no-color -detailed-exitcode | tee terraform-plan.log # Añado -no-color para quitar el formato terminal para plancharlo en texto plano
        continue-on-error: true 

      - name: Upload Terraform Plan Log # Añado la subida de artefacto de log para poder tener control de la creacion y modificacion de la infraestructura
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-log
          path: terraform-plan.log

      - name: Terraform Apply (if changes detected)
        if: steps.plan.outcome == 'success' && steps.plan.outputs.exitcode == 2
        run: terraform apply -auto-approve tfplan
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Verify Deployment
        run: kubectl get pods -n mynamespace